CREATE TABLE USERS ( 
         login varchar(255),
         id integer,
         user_id serial,
         node_id varchar(255),
         avatar_url varchar(255), 
         gravatar_id varchar(255),
         url varchar(255), 
         html_url varchar(255),
         followers_url varchar(255),
         following_url varchar(255),
         gists_url varchar(255),
         starred_url varchar(255),
         subscriptions_url varchar(255),
         organizations_url varchar(255),
         repos_url varchar(255),
         events_url varchar(255), 
         received_events_url varchar(255),
         type varchar(255),
         site_admin boolean,
		 PRIMARY KEY(user_id)
)

CREATE TABLE Topics (
		 topics_id varchar(255),
		 PRIMARY KEY (topics_id)
)

CREATE TABLE Repos (
		 repos_id serial,  
         id integer, 
         node_id varchar(255),
         name varchar(255),
         full_name varchar(255),
         owner integer, 
         is_private boolean, 
         html_url varchar(255),
         description varchar(255),
         fork varchar(255),
         url varchar (255),
         archive_url varchar(255),
         assignees_url varchar(255),
         blobs_url varchar(255),
         branches_url varchar(255), 
         collaborators_url varchar(255),
         comments_url varchar(255),
         commits_url varchar(255),
         compare_url  varchar(255),
         contents_url varchar(255),
         contributors_url varchar(255),
         deployments_url varchar(255),
         downloads_url varchar(255),
         events_url varchar(255),
         forks_url  varchar(255),
         git_commits_url varchar(255), 
         git_refs_url varchar(255), 
         git_tags_url varchar(255), 
         git_url varchar(255), 
         issue_comment_url varchar(255), 
         issue_events_url varchar(255), 
         issues_url varchar(255), 
         keys_url varchar(255), 
         labels_url varchar(255), 
         languages_url varchar(255), 
         merges_url varchar(255),
         milestones_url varchar(255),
         notifications_url varchar(255), 
         pulls_url varchar(255),
         releases_url varchar(255), 
         ssh_url varchar(255), 
         stargazers_url varchar(255), 
         statuses_url varchar(255), 
         subscribers_url varchar(255), 
         subscription_url varchar(255), 
         tags_url varchar(255), 
         teams_url varchar(255), 
         trees_url varchar(255), 
         clone_url varchar(255), 
         mirror_url varchar(255), 
         hooks_url varchar(255), 
         svn_url varchar(255), 
         homepage varchar(255), 
         language varchar(255),
         forks_count integer,
         stargazers_count integer, 
         watchers_count integer,
         size integer,
         default_branch varchar(255),
         open_issues_count integer,
         is_template boolean,
         topics_id integer,
         has_issues boolean,
         has_projects boolean,
         has_wiki boolean,
         has_pages boolean,
         has_downloads boolean,
         archived boolean,
         disabled boolean,
         pushed_at timestamp,
         created_at timestamp,
         updated_at timestamp,
         perm_can_push boolean,
         perm_is_admin boolean,
         perm_can_pull boolean,
         template_repository varchar(255),
         subscribers_count integer,
         network_count integer,
		 PRIMARY KEY(repos_id),
		 CONSTRAINT Repos_Users_owner FOREIGN KEY (owner)
		 REFERENCES Users(user_id)
		 )
		 
		 
CREATE TABLE ReposTopics (
		 topics_id varchar(255),
		 repos_id integer,
		 PRIMARY KEY(topics_id, repos_id),
		 CONSTRAINT RepoTopics_Repos_repos_id FOREIGN KEY (repos_id)
		 REFERENCES Repos(repos_id),
		 CONSTRAINT RepoTopics_Topics_topics_id FOREIGN KEY (topics_id)
		 REFERENCES Topics(topics_id)
)
